# Generated by Django 2.2.1 on 2019-05-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('name_servicio', models.CharField(help_text='Ingrese el nombre del servicio.', max_length=100)),
                ('date_since', models.DateField()),
                ('date_until', models.DateField(blank=True, null=True)),
                ('deactivate_servicio', models.BooleanField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1, help_text='Estado del servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id_subarea', models.IntegerField(primary_key=True, serialize=False)),
                ('name_subarea', models.CharField(help_text='Ingrese el nombre de la subarea.', max_length=100)),
                ('date_since', models.DateField()),
                ('date_until', models.DateField(blank=True, null=True)),
                ('deactivate_subarea', models.BooleanField(blank=True, choices=[(0, 'Inactivo'), (1, 'Activo')], default=1, help_text='Estado de la subarea')),
                ('id_servicio', models.ForeignKey(help_text='Ingrese servicio para la subarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('name_cuenta', models.CharField(help_text='Ingrese nombre de la cuenta', max_length=100)),
                ('date_since', models.DateField()),
                ('data_until', models.DateField(blank=True, null=True)),
                ('deactivate_cuenta', models.BooleanField(default=0)),
                ('id_subarea', models.ForeignKey(help_text='Ingrese la subarea para la cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Subarea')),
            ],
        ),
    ]
