# Generated by Django 2.2.1 on 2019-05-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190531_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='deactivate_cuenta',
            field=models.BooleanField(blank=True, choices=[(0, 'Inactivo'), (1, 'Activo')], default=1, help_text='Estado de la cuenta'),
        ),
    ]
