# Generated by Django 2.2.1 on 2019-06-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190531_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='id_subarea',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='id_subarea',
            field=models.ManyToManyField(help_text='Ingrese la subarea para la cuenta', null=True, to='reports.Subarea'),
        ),
    ]
