# Generated by Django 2.2.1 on 2019-06-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190531_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='data_until',
            new_name='date_until',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='id_subarea',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='id_servicio',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('name_report', models.CharField(help_text='Ingrese nombre del reporte.', max_length=100)),
                ('date_since', models.DateField(help_text='Ingrese fecha de inicio de actividad')),
                ('date_until', models.DateField(help_text='Ingrese fecha de fin de actividad')),
                ('status_report', models.BooleanField()),
                ('id_cuenta', models.ForeignKey(blank=True, help_text='Ingrese nombre de la cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Cuenta')),
                ('id_servicio', models.ForeignKey(blank=True, help_text='Ingrese Nombre del servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Servicio')),
                ('id_subarea', models.ForeignKey(blank=True, help_text='Ingrese nombre de la sub-area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Subarea')),
            ],
        ),
    ]
