# Generated by Django 2.2.1 on 2019-06-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190601_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Reporte',
        ),
    ]
