# Generated by Django 2.2.1 on 2019-06-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190601_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='status_report',
            field=models.BooleanField(choices=[(0, 'Inactivo'), (1, 'Activo')]),
        ),
    ]
