# Generated by Django 2.2.1 on 2019-06-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190601_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='date_until',
            field=models.DateField(blank=True, help_text='Ingrese fecha de fin de actividad', null=True),
        ),
    ]
