# Generated by Django 2.2.1 on 2019-06-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190601_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['id_report']},
        ),
    ]
